# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - paralleltest
    - revive
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gosec:
      config:
        G302: "0644" # Allow creating file with mode 0644

formatters:
  enable:
    - gci
    - gofmt
    # - gofumpt
    - goimports
    # - golines
