# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - execinquery
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gofumpt
    - gomnd
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
