// Copyright (c) Illumio, Inc.
// SPDX-License-Identifier: MPL-2.0

package schema

import (
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	resource_schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var SupportedIconTypes = []string{
	"access",
	"across-enf-boundary-rtl",
	"across-enf-boundary",
	"ad-certificate",
	"ad-federation",
	"ad-lightweight-directory",
	"ad-rights-management",
	"ad",
	"add-diff-classic",
	"add-diff",
	"add-user",
	"add",
	"adfs",
	"admin",
	"ai-star-no-fill",
	"ai-star",
	"all-workloads",
	"allowlist",
	"amazon-cognito",
	"any",
	"app-group-map",
	"app",
	"appgroup",
	"application-definition-banner-modal",
	"application-definition",
	"application",
	"arrow-curve-left-down",
	"arrow-curve-left-up",
	"arrow-curve-left",
	"arrow-curve-right-down",
	"arrow-curve-right-up",
	"arrow-down-bold",
	"arrow-down-bolder",
	"arrow-down",
	"arrow-left-long",
	"arrow-left-to-bracket",
	"arrow-left",
	"arrow-right-long",
	"arrow-right",
	"arrow-switch-horizontal",
	"arrow-switch-vertical",
	"arrow-up-bold",
	"arrow-up-bolder",
	"arrow-up-down-switch",
	"arrow-up",
	"audit",
	"auth0",
	"aws-white",
	"aws",
	"azure",
	"back-classic",
	"back",
	"bi-directional",
	"bolt-filled",
	"bookmark",
	"brush-activate",
	"brush-clear",
	"brush-pause",
	"calendar",
	"cancel",
	"cannot-write-rules",
	"capslock",
	"chart-curvy",
	"chart-straight",
	"check-classic",
	"check-filled",
	"check",
	"chevron-double-left",
	"chevron-double-right",
	"circle-stop",
	"clear",
	"clipboard-list",
	"close-classic",
	"close",
	"cloud-custom",
	"cloud-workload",
	"cloud",
	"collapse-all",
	"collapse-role",
	"column",
	"comment-classic",
	"comment",
	"container-workload",
	"copy-new",
	"copy",
	"corporate",
	"critical",
	"customize-axis",
	"dashboard-classic",
	"dashboard",
	"database",
	"decrease",
	"delete",
	"deny",
	"denylist",
	"deployment",
	"destination",
	"disabled-none",
	"disabled-status-classic",
	"disabled-status",
	"disabled",
	"discover-rule-banner-modal",
	"discovery-rule",
	"document",
	"down-classic",
	"down",
	"download-lightning",
	"download",
	"duplicate",
	"edit-classic",
	"edit-underline",
	"edit",
	"email",
	"enabled",
	"endpoint",
	"enf-boundary-rtl",
	"enf-boundary",
	"enforce",
	"enforced",
	"env-classic",
	"env",
	"error-boundary",
	"error-classic",
	"error-filled",
	"error",
	"expand-role",
	"expand",
	"explore",
	"export",
	"external-link-classic",
	"external-link",
	"file-copy",
	"file",
	"filter-advanced",
	"filter-widget",
	"filter",
	"flip-horizontal",
	"flip-vertical",
	"folder-filled",
	"folder",
	"gcp",
	"global-map",
	"global-rule",
	"google-cloud",
	"google-identity-platform",
	"grab-handle-classic",
	"grab-handle",
	"graph-icon",
	"grid",
	"group",
	"health",
	"help-classic",
	"help-menu",
	"help",
	"home-filled",
	"how-to-read",
	"howToRead-enforcement",
	"howToRead-vulnerability",
	"id",
	"idle",
	"illuminate",
	"illumination",
	"illumio-glyph",
	"illumio-logo",
	"illumio_glyph",
	"impact",
	"import",
	"increase",
	"info-classic",
	"info-filled",
	"info",
	"infrastructure",
	"inspect",
	"internet",
	"inuse-classic",
	"inuse-full",
	"inuse",
	"ip-lists",
	"jira",
	"key",
	"kubernetes-workload",
	"layout-reset",
	"layout",
	"ldap",
	"left",
	"legend",
	"lightbulb-outline",
	"lightning-filter",
	"link-new",
	"link",
	"list",
	"loading",
	"loc-outline",
	"loc",
	"local",
	"lock-rounded",
	"lock",
	"machine-auth",
	"manage",
	"managed-tenants",
	"map-ai-indicator",
	"map-link-down",
	"map-link-left",
	"map-link",
	"map-no-border",
	"map",
	"member-hide",
	"member-show",
	"menu",
	"mesh",
	"mode",
	"more-grid",
	"more-horizontal",
	"more",
	"move-tool",
	"ms-entra-id",
	"navigateup",
	"network",
	"next-classic",
	"next",
	"node-size",
	"non-corporate",
	"oci",
	"oidc",
	"okta",
	"oneLogin",
	"online",
	"org",
	"overflow",
	"pair",
	"parallel-icon",
	"pause",
	"pce-health",
	"pen-ruler",
	"pending",
	"pin",
	"pingIdentity",
	"play-outline",
	"play",
	"policy",
	"policyobj",
	"pop-in-classic",
	"pop-in",
	"pop-out-classic",
	"pop-out",
	"potentially-blocked",
	"private-address",
	"progress-partial",
	"progress",
	"provision-classic",
	"provision",
	"refresh-classic",
	"refresh-clock",
	"refresh",
	"remote-desktop",
	"remove-diff-classic",
	"remove-diff",
	"remove-square",
	"remove",
	"reset",
	"resize-handle",
	"revert",
	"right-classic",
	"right",
	"risk",
	"role",
	"run",
	"saml",
	"save",
	"scope",
	"search-alt",
	"search-classic",
	"search",
	"secure-connect",
	"selected",
	"selection-tool",
	"send",
	"server",
	"servers-endpoints",
	"servers",
	"service-category-placeholder",
	"service-category",
	"service-role-placeholder",
	"service-role",
	"service",
	"settings-classic",
	"settings",
	"slack",
	"sort-down",
	"sort-up",
	"sort",
	"source",
	"staged",
	"star-outline",
	"star",
	"stars",
	"starter-page-graphic",
	"stop",
	"stopped",
	"suspended",
	"syncing",
	"t2l",
	"table-list-close",
	"table-list-open",
	"table",
	"third-party",
	"thumbs-down-hollow",
	"thumbs-down",
	"thumbs-up-hollow",
	"thumbs-up",
	"time-count",
	"time",
	"traffic",
	"troubleshoot",
	"unlink",
	"unlock",
	"unlocked",
	"unmanaged",
	"unpair",
	"up-classic",
	"up",
	"upload",
	"usage",
	"user-add-new",
	"user",
	"userprof",
	"ven",
	"version",
	"video",
	"virtual-server",
	"virtual-service",
	"warning-classic",
	"warning-filled",
	"warning",
	"workload",
	"zoom-in",
	"zoom-out",
	"zoom-to-fit-classic",
	"zoom-to-fit",
}

var (
	tagToLabelResource = Resource{
		TypeName: "tag_to_label",
		Schema: resource_schema.Schema{
			Version:             1,
			MarkdownDescription: "Maps cloud resource tags to CloudSecure labels.",
			Attributes: map[string]resource_schema.Attribute{
				IDFieldName: idAttribute,
				"aws_tag_keys": resource_schema.SetAttribute{
					Description: "Sets of keys of AWS resource tags to map to CloudSecure labels with the same keys. The values of the created labels correspond to the values of the tags.",
					Required:    true,
					ElementType: types.StringType,
				},
				"azure_tag_keys": resource_schema.SetAttribute{
					Description: "Set of keys of Azure resource tags to map to CloudSecure labels with the same keys. The values of the created labels correspond to the values of the tags.",
					Required:    true,
					ElementType: types.StringType,
				},
				"icon": resource_schema.ObjectAttribute{
					MarkdownDescription: "Icon of the created CloudSecure labels. The supported icon names are: \n > ``` " + strings.Join(SupportedIconTypes, ", ") + " ```",
					Required:            true,
					AttributeTypes: map[string]attr.Type{
						"name":             types.StringType,
						"background_color": types.StringType,
						"foreground_color": types.StringType,
					},
				},
				"key": resource_schema.StringAttribute{
					MarkdownDescription: "Key of the created CloudSecure labels.",
					Required:            true,
				},
				"name": resource_schema.StringAttribute{
					MarkdownDescription: "Display name of the created CloudSecure labels.",
					Required:            true,
				},
			},
		},
	}
)
