name: golangci-test
on:
    push:
        branches:
            - main
        paths:
            - '**.go'
    pull_request:
        branches:
            - main
        paths:
            - '**.go'

permissions:
    contents: read
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...
